# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65a700fcfecd744230a323d57bfd35822818a50466df1531c8c33caed7c268255703d8425feb4dd6f37c98bfe9543cdad42ed8b67a584b342bb98b80ebe08ad3

test:
  secret_key_base: be11403dbe26c61b8b5dd49f2c38c602ccc4f4f380f58ff47c9642aa159bdfa7061e5b37250f326c8b56564653f71bb629e3984400f4ee2a90898f3c85c6fa32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
