# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d979eb0a5ec55fbabdc12c229cbb49a24661887a7547034ed9a97be3871deba039af1f721227ad6a765427f6b86adef8f5f90c12494248858decb37409a6c4c

test:
  secret_key_base: c904161f6dff555cb4add5e5ee0b0b5c9c0830cb3a1d38603a8786f77a8f397b83e0d665d2b78fc3682cf14ee6343fc9258f74cce38824ce304ea26c894479c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
