# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be57611768f8d8ca34c38b95c663e557a2e754a9d77a7e1bc3f685eba5243577dc2848bdaab7204081829b4ea2e6f53e748314988eaf1e6012b65a324e75ea80

test:
  secret_key_base: 8b6a8c250a0826a3ac23ff7fe10b2a2b3993536c5776c4dd72b64239dc4b2e7d7eab519faea0cfa3743f6a6305e1caa222812e7532068679103ead1dc322e8f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
